modLoader="javafml"
loaderVersion="[38,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/quat1024/apathy/issues"

[[mods]]
modId="apathy"
version="${file.jarVersion}" # TODO
displayName="Apathy"
displayURL="https://github.com/quat1024/apathy/"
logoFile="apathy-icon-128.png"
credits="jaredl0008 and Darkhax for MultiLoader-Template"
authors="quaternary"
description="Mobs don't attack players. Or maybe they do! Configurable! Yay"

## A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
#[[dependencies.multiloader]] #optional
## the modid of the dependency
#modId="forge" #mandatory
## Does this dependency have to exist - if not, ordering below must be specified
#mandatory=true #mandatory
## The version range of the dependency
#versionRange="[38,)" #mandatory
## An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
#ordering="NONE"
## Side this dependency is applied on - BOTH, CLIENT or SERVER
#side="BOTH"
## Here's another dependency
#[[dependencies.multiloader]]
#modId="minecraft"
#mandatory=true
## This version range declares a minimum of the current minecraft version up to but not including the next major version
#versionRange="[1.18,1.19)"
#ordering="NONE"
#side="BOTH"
